src/blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.post_list, name='post_list'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<post>[-\w]+)/$', views.post_detail, name='post_detail'),
]

src/cart/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)$', views.cart_remove, name='cart_remove'),
]

src/home/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
]

src/shop/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.product_list, name='product_list'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
]

src/src/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', include('home.urls', namespace='home')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^shop/', include('shop.urls', namespace='shop')),
    url(r'^cart/', include('cart.urls', namespace='cart')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from tinymce.models import HTMLField
from django.core.urlresolvers import reverse

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')


class Post(models.Model):
    objects = models.Manager()
    published = PublishedManager()
    STATUS_CHISES = (
        ('draft', 'Roboczy'),
        ('published', 'Opublikowany')
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=255, unique_for_date='publish')
    author = models.ForeignKey(User, related_name='blog_posts')
    body = HTMLField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHISES, default='draft')

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.publish.year, self.publish.strftime('%m'), self.publish.strftime('%d'), self.slug])

src/cart/models.py
from django.db import models

# Create your models here.

src/home/models.py
from django.db import models

# Create your models here.

src/shop/models.py
from django.db import models
from django.core.urlresolvers import reverse

class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])

class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products')
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])

src/cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

src/blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post

def post_list(request):
    posts = Post.published.all()
    return render(request, 'blog/post/list.html', {'posts': posts})

def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post, status='published', publish__year=year, publish__month=month, publish__day=day)
    return render(request, 'blog/post/detail.html', {'post': post})

src/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm

@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'])
    return redirect('cart:cart_detail')

def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    return render(request, 'cart/detail.html', {'cart': cart})

src/home/views.py
from django.shortcuts import render

def home(request):
    return render(request, 'home/home.html')

src/shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from cart.forms import CartAddProductForm

def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request, 'shop/product/list.html', {'category': category, 'categories': categories, 'products': products})

def product_detail(request, id, slug):
    category = None
    categories = Category.objects.all()
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()
    return render(request, 'shop/product/detail.html', {'category': category, 'categories': categories, 'product': product, 'cart_product_form': cart_product_form})

src/blog/templates/blog/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>{% block title %}Blog{% endblock %}</title>
        <link rel="stylesheet" href="{% static "css/bootstrap.css" %}">
        <link rel="stylesheet" href="{% static "css/bs.css" %}">
    </head>
    <body>
        <header>
            <nav class="navbar navbar-inverse">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <button type="button" class="collapsed navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-9" aria-expanded="false">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a href="/" class="navbar-brand">Home</a>
                    </div>
                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-9">
                        <ul class="nav navbar-nav">
                            <li class="active"><a href="/blog/">Blog</a></li>
                            <li><a href="/shop/">Shop</a></li>
                            <li><a href="/admin/">Panel</a></li>
                        </ul>
                    </div>
                </div>
            </nav>
        </header>
        <main>
            {% block content %}
            {% endblock %}
        </main>
    </body>
</html>

src/blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load staticfiles %}

{% block title %}
    Blog
{% endblock %}

{% block content %}
<article class="container">
    <header>
        <h1>
            {{ post.title }}
        </h1>
    </header>
    <div class="well">
        {{ post.body|safe }}
    </div>
    <footer>
        Opublikowany <time>{{ post.publish }}</time> przez <author>{{ post.author }}</author>
    </footer>
</article>
{% endblock %}

src/blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load staticfiles %}

{% block title %}
    Blog
{% endblock %}

{% block content %}
<section class="container">
    <header>
        <h1>
            Blog
        </h1>
    </header>
    <div class="bs-docs-section">
        {% for post in posts %}
            <article class="bs-callout bs-callout-info">
                <header>
                    <h2>
                        <a href="{{ post.get_absolute_url }}">
                            {{ post.title }}
                        </a>
                    </h2>
                </header>
                <div>
                    {{ post.body|striptags|safe|truncatewords:30|linebreaks }}
                </div>
                <footer class="text-right">
                    <em>
                        Opublikowany <time>{{ post.publish }}</time> przez <author>{{ post.author }}</author>
                    </em>
                </footer>
            </article>
        {% endfor %}
    </div>
</section>
{% endblock %}

src/cart/templates/cart/detail.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
Shoping cart
{% endblock %}

{% block content %}
<div class="container">
    <div class="well">
        <h1>Shoping cart</h1>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Image</th>
                    <th>Product</th>
                    <th>Count</th>
                    <th>Remove</th>
                    <th>Price</th>
                    <th>Total price</th>
                </tr>
            </thead>
            <tbody>
                {% for item in cart %}
                    {% with product=item.product %}
                        <tr>
                            <td>
                                <a href="{{ product.get_absolute_url }}">
                                    <img src="{% if product.image %}
                                        {{ product.image.url }}
                                    {% else %}
                                        {% static "img/no_image.png" %}
                                    {% endif %}" alt="{{ product.name }}" width="200">
                                </a>
                            </td>
                            <td>{{ product.name }}</td>
                            <td>{{ item.quantity }}</td>
                            <td>
                                <a href="{% url "cart:cart_remove" product.id %}">Remove</a>
                            </td>
                            <td>{{ item.price }} PLN</td>
                            <td>{{ item.total_price }} PLN</td>
                        </tr>
                    {% endwith %}
                {% endfor %}
                <tr>
                    <td>Total price</td>
                    <td colspan="4"></td>
                    <td>{{ cart.get_total_price }} PLN</td>
                </tr>
            </tbody>
        </table>
        <div class="btn-group">
            <a href="{% url "shop:product_list" %}" class="btn btn-success">Continue shoping</a>
            <a href="#" class="btn btn-primary">To cash</a>
        </div>
    </div>
</div>
{% endblock %}

src/home/templates/home/home.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>CMS project inf108589</title>
        <link rel="stylesheet" href="{% static "css/bootstrap.css" %}">
        <link rel="stylesheet" href="{% static "css/base.css" %}">
    </head>
    <body>
        <header>
            <nav class="navbar navbar-inverse">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <button type="button" class="collapsed navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-9" aria-expanded="false">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a href="/" class="navbar-brand">Home</a>
                    </div>
                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-9">
                        <ul class="nav navbar-nav">
                            <li><a href="/blog/">Blog</a></li>
                            <li><a href="/shop/">Shop</a></li>
                            <li><a href="/admin/">Panel</a></li>
                        </ul>
                    </div>
                </div>
            </nav>
        </header>
        <div class="container">
            <div class="jumbotron">
                <header>
                    <h1>CMS project</h1>
                    <p>inf108589</p>
                </header>
                <p>
                    <a class="btn btn-primary btn-lg" href="/blog/" role="button">Blog</a>
                    <a class="btn btn-primary btn-lg" href="/shop/" role="button">Shop</a>
                    <a class="btn btn-primary btn-lg" href="/admin/" role="button">Panel</a>
                </p>
            </div>
        </div>
    </body>
</html>

src/shop/templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>{% block title %}Shop{% endblock %}</title>
        <link rel="stylesheet" href="{% static "css/bootstrap.css" %}">
        <link rel="stylesheet" href="{% static "css/base.css" %}">
    </head>
    <body>
        <header>
            <nav class="navbar navbar-inverse">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <button type="button" class="collapsed navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-9" aria-expanded="false">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a href="/" class="navbar-brand">Home</a>
                    </div>
                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-9">
                        <ul class="nav navbar-nav">
                            <li><a href="/blog/">Blog</a></li>
                            <li class="active"><a href="/shop/">Shop</a></li>
                            <li><a href="/admin/">Panel</a></li>
                        </ul>
                    </div>
                </div>
            </nav>
        </header>
        <main>
            {% block content %}
            {% endblock %}
        </main>
    </body>
</html>

src/shop/templates/shop/product/detail.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
    {% if category %}
        {{ category.name }}
    {% else %}
        Products
    {% endif %}
{% endblock %}

{% block content %}
<div class="container">
    <div class="well row">
        <div class="col-sm-3">
            <h3>Categories</h3>
            <div class="list-group">
                <a class="list-group-item" href="{% url "shop:product_list" %}">All</a>
                {% for c in categories %}
                    <a class="{% if product.category.slug == c.slug %}active {% endif %}list-group-item" href="{{ c.get_absolute_url }}">{{ c.name }}</a>
                {% endfor %}
            </div>
        </div>
        <div class="col-sm-9">
            <h1>
                {{ product.name }}
            </h1>
            <h2>
                <a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a>
            </h2>

            <img src="{% if product.image %}
                {{ product.image.url }}
            {% else %}
                {% static "img/on_image.png" %}
            {% endif %}" alt="" class="img-thumbnail">

            <div>
                <span class="label label-default">{{ product.price }} PLN</span>

                <form action="{% url "cart:cart_add" product.id %}" method="post">
                    {{ cart_product_form }}
                    {% csrf_token %}
                    <button class="btn btn-default" type="submit">Add to cart</button>
                </form>

                {{ product.description|linebreaks }}
            </div>
        </div>
    </div>
</div>
{% endblock %}

src/shop/templates/shop/product/list.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
    {% if category %}
        {{ category.name }}
    {% else %}
        Products
    {% endif %}
{% endblock %}

{% block content %}
<div class="container">
    <div class="well row">
        <div class="col-sm-3">
            <h3>Categories</h3>
            <div class="list-group">
                <a class="{% if not category %}active {% endif %}list-group-item" href="{% url "shop:product_list" %}">All</a>
                {% for c in categories %}
                    <a class="{% if category.slug == c.slug %}active {% endif %}list-group-item" href="{{ c.get_absolute_url }}">{{ c.name }}</a>
                {% endfor %}
            </div>
        </div>
        <div class="col-sm-9">
            <h1>
                {% if category %}
                    {{ category.name }}
                {% else %}
                    Products
                {% endif %}
            </h1>
            <div class="row">
                {% for product in products %}
                    <div class="col-sm-4">
                        <a href="{{ product.get_absolute_url }}">
                            <img src="{% if product.image %}
                                {{ product.image.url }}
                            {% else %}
                                {% static "img/on_image.png" %}
                            {% endif %}" alt="" class="img-thumbnail">
                        </a>
                        <div>
                            <a href="{{ product.get_absolute_url }}"><b>{{ product.name }}</b></a><br>
                            <span class="label label-default">{{ product.price }} PLN</span>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}